package com.spider4j.spider.webspider.model;

import java.util.Date;

public class Stock_ind1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.md5url
     *
     * @mbggenerated
     */
    private String md5url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.test
     *
     * @mbggenerated
     */
    private Short test;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.icon_title
     *
     * @mbggenerated
     */
    private String iconTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.keyword1
     *
     * @mbggenerated
     */
    private String keyword1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.wbid
     *
     * @mbggenerated
     */
    private Long wbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.writer
     *
     * @mbggenerated
     */
    private String writer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.reporter
     *
     * @mbggenerated
     */
    private String reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.release_time
     *
     * @mbggenerated
     */
    private String releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.page_view
     *
     * @mbggenerated
     */
    private Integer pageView;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.pra_num
     *
     * @mbggenerated
     */
    private Integer praNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.cmt_num
     *
     * @mbggenerated
     */
    private Integer cmtNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.ret_num
     *
     * @mbggenerated
     */
    private Integer retNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.read_num
     *
     * @mbggenerated
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.srctypeid
     *
     * @mbggenerated
     */
    private Integer srctypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.datatype
     *
     * @mbggenerated
     */
    private Byte datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.rank
     *
     * @mbggenerated
     */
    private Float rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.score
     *
     * @mbggenerated
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.hmflag
     *
     * @mbggenerated
     */
    private Byte hmflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ind1.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.id
     *
     * @return the value of stock_ind1.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.id
     *
     * @param id the value for stock_ind1.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.md5url
     *
     * @return the value of stock_ind1.md5url
     *
     * @mbggenerated
     */
    public String getMd5url() {
        return md5url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.md5url
     *
     * @param md5url the value for stock_ind1.md5url
     *
     * @mbggenerated
     */
    public void setMd5url(String md5url) {
        this.md5url = md5url == null ? null : md5url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.test
     *
     * @return the value of stock_ind1.test
     *
     * @mbggenerated
     */
    public Short getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.test
     *
     * @param test the value for stock_ind1.test
     *
     * @mbggenerated
     */
    public void setTest(Short test) {
        this.test = test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.title
     *
     * @return the value of stock_ind1.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.title
     *
     * @param title the value for stock_ind1.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.icon_title
     *
     * @return the value of stock_ind1.icon_title
     *
     * @mbggenerated
     */
    public String getIconTitle() {
        return iconTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.icon_title
     *
     * @param iconTitle the value for stock_ind1.icon_title
     *
     * @mbggenerated
     */
    public void setIconTitle(String iconTitle) {
        this.iconTitle = iconTitle == null ? null : iconTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.category
     *
     * @return the value of stock_ind1.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.category
     *
     * @param category the value for stock_ind1.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.keyword
     *
     * @return the value of stock_ind1.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.keyword
     *
     * @param keyword the value for stock_ind1.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.keyword1
     *
     * @return the value of stock_ind1.keyword1
     *
     * @mbggenerated
     */
    public String getKeyword1() {
        return keyword1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.keyword1
     *
     * @param keyword1 the value for stock_ind1.keyword1
     *
     * @mbggenerated
     */
    public void setKeyword1(String keyword1) {
        this.keyword1 = keyword1 == null ? null : keyword1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.wbid
     *
     * @return the value of stock_ind1.wbid
     *
     * @mbggenerated
     */
    public Long getWbid() {
        return wbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.wbid
     *
     * @param wbid the value for stock_ind1.wbid
     *
     * @mbggenerated
     */
    public void setWbid(Long wbid) {
        this.wbid = wbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.openid
     *
     * @return the value of stock_ind1.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.openid
     *
     * @param openid the value for stock_ind1.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.writer
     *
     * @return the value of stock_ind1.writer
     *
     * @mbggenerated
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.writer
     *
     * @param writer the value for stock_ind1.writer
     *
     * @mbggenerated
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.reporter
     *
     * @return the value of stock_ind1.reporter
     *
     * @mbggenerated
     */
    public String getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.reporter
     *
     * @param reporter the value for stock_ind1.reporter
     *
     * @mbggenerated
     */
    public void setReporter(String reporter) {
        this.reporter = reporter == null ? null : reporter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.release_time
     *
     * @return the value of stock_ind1.release_time
     *
     * @mbggenerated
     */
    public String getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.release_time
     *
     * @param releaseTime the value for stock_ind1.release_time
     *
     * @mbggenerated
     */
    public void setReleaseTime(String releaseTime) {
        this.releaseTime = releaseTime == null ? null : releaseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.publish_time
     *
     * @return the value of stock_ind1.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.publish_time
     *
     * @param publishTime the value for stock_ind1.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.page_view
     *
     * @return the value of stock_ind1.page_view
     *
     * @mbggenerated
     */
    public Integer getPageView() {
        return pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.page_view
     *
     * @param pageView the value for stock_ind1.page_view
     *
     * @mbggenerated
     */
    public void setPageView(Integer pageView) {
        this.pageView = pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.pra_num
     *
     * @return the value of stock_ind1.pra_num
     *
     * @mbggenerated
     */
    public Integer getPraNum() {
        return praNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.pra_num
     *
     * @param praNum the value for stock_ind1.pra_num
     *
     * @mbggenerated
     */
    public void setPraNum(Integer praNum) {
        this.praNum = praNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.cmt_num
     *
     * @return the value of stock_ind1.cmt_num
     *
     * @mbggenerated
     */
    public Integer getCmtNum() {
        return cmtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.cmt_num
     *
     * @param cmtNum the value for stock_ind1.cmt_num
     *
     * @mbggenerated
     */
    public void setCmtNum(Integer cmtNum) {
        this.cmtNum = cmtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.ret_num
     *
     * @return the value of stock_ind1.ret_num
     *
     * @mbggenerated
     */
    public Integer getRetNum() {
        return retNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.ret_num
     *
     * @param retNum the value for stock_ind1.ret_num
     *
     * @mbggenerated
     */
    public void setRetNum(Integer retNum) {
        this.retNum = retNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.read_num
     *
     * @return the value of stock_ind1.read_num
     *
     * @mbggenerated
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.read_num
     *
     * @param readNum the value for stock_ind1.read_num
     *
     * @mbggenerated
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.srctypeid
     *
     * @return the value of stock_ind1.srctypeid
     *
     * @mbggenerated
     */
    public Integer getSrctypeid() {
        return srctypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.srctypeid
     *
     * @param srctypeid the value for stock_ind1.srctypeid
     *
     * @mbggenerated
     */
    public void setSrctypeid(Integer srctypeid) {
        this.srctypeid = srctypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.datatype
     *
     * @return the value of stock_ind1.datatype
     *
     * @mbggenerated
     */
    public Byte getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.datatype
     *
     * @param datatype the value for stock_ind1.datatype
     *
     * @mbggenerated
     */
    public void setDatatype(Byte datatype) {
        this.datatype = datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.rank
     *
     * @return the value of stock_ind1.rank
     *
     * @mbggenerated
     */
    public Float getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.rank
     *
     * @param rank the value for stock_ind1.rank
     *
     * @mbggenerated
     */
    public void setRank(Float rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.score
     *
     * @return the value of stock_ind1.score
     *
     * @mbggenerated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.score
     *
     * @param score the value for stock_ind1.score
     *
     * @mbggenerated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.hmflag
     *
     * @return the value of stock_ind1.hmflag
     *
     * @mbggenerated
     */
    public Byte getHmflag() {
        return hmflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.hmflag
     *
     * @param hmflag the value for stock_ind1.hmflag
     *
     * @mbggenerated
     */
    public void setHmflag(Byte hmflag) {
        this.hmflag = hmflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.status
     *
     * @return the value of stock_ind1.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.status
     *
     * @param status the value for stock_ind1.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ind1.update_time
     *
     * @return the value of stock_ind1.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ind1.update_time
     *
     * @param updateTime the value for stock_ind1.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}