package com.spider4j.spider.webspider.model;

import java.util.Date;

public class UrlIndex {

    private String id;

    private String url;

    private String host;

    private UrlType urlType;

    private Date date;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column spider4j_url_index.id
     * 
     * @param id the value for spider4j_url_index.id
     * 
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public UrlType getUrlType() {
        return urlType;
    }

    public void setUrlType(UrlType urlType) {
        this.urlType = urlType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column spider4j_url_index.url
     * 
     * @return the value of spider4j_url_index.url
     * 
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column spider4j_url_index.url
     * 
     * @param url the value for spider4j_url_index.url
     * 
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column spider4j_url_index.host
     * 
     * @return the value of spider4j_url_index.host
     * 
     * @mbggenerated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column spider4j_url_index.host
     * 
     * @param host the value for spider4j_url_index.host
     * 
     * @mbggenerated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column spider4j_url_index.date
     * 
     * @return the value of spider4j_url_index.date
     * 
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column spider4j_url_index.date
     * 
     * @param date the value for spider4j_url_index.date
     * 
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}